include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/dtos/*.g.dart
    - lib/dtos/*.freezed.dart
    - lib/firebase_options.dart

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods