name: application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: 3.24.0

dependencies:
  cached_network_image: ^3.4.0
  crop_your_image: ^1.1.0
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  like_button: ^2.0.5
  palette_generator: ^0.3.3+4
  restart_app:
    git:
      url: https://github.com/Shikkanime/restart_app.git
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  vibration: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.12
  dart_code_metrics_presets: ^2.16.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: 'assets/splash.png'
  android_12:
    color: "#000000"
    image: 'assets/splash.png'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon_450x450.png
    - assets/splash.png
    - shorebird.yaml
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.ttf
        - asset: assets/fonts/satoshi/Satoshi-Regular.ttf
        - asset: assets/fonts/satoshi/Satoshi-Medium.ttf
        - asset: assets/fonts/satoshi/Satoshi-Bold.ttf
        - asset: assets/fonts/satoshi/Satoshi-Italic.ttf
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.ttf
