name: application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.11+14

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  cached_network_image: ^3.4.1
  crop_your_image: ^2.0.0
  firebase_analytics: ^12.0.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  image_picker: ^1.2.0
  in_app_review: ^2.0.11
  in_app_update: ^4.2.5
  intl: 0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  restart_app: ^1.3.2
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  shorebird_code_push: ^2.0.5
  url_launcher: ^6.3.2
  vibration: ^3.1.4

dev_dependencies:
  build_runner: ^2.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter_launcher_icons:
  image_path: 'assets/icon.png'
  adaptive_icon_background: 'assets/icon.png'
  adaptive_icon_foreground: 'assets/icon.png'
  android: true
  adaptive_icon_monochrome: 'assets/monochrome.png'
  ios: true
  image_path_ios_tinted_grayscale: 'assets/grayscale.png'
  desaturate_tinted_to_grayscale_ios: true
  windows:
    generate: true
    image_path: 'assets/light_icon.png'
    icon_size: 128

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/dark_icon_padding.png'
  image_dark: 'assets/light_icon_padding.png'
  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: 'assets/dark_icon_padding.png'
    image_dark: 'assets/light_icon_padding.png'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/light_icon.png
    - assets/dark_icon.png
    - shorebird.yaml
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.ttf
        - asset: assets/fonts/satoshi/Satoshi-Regular.ttf
        - asset: assets/fonts/satoshi/Satoshi-Medium.ttf
        - asset: assets/fonts/satoshi/Satoshi-Bold.ttf
        - asset: assets/fonts/satoshi/Satoshi-Italic.ttf
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.ttf
