name: application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: any
  json_annotation: ^4.8.1
  like_button: ^2.0.5
  url_launcher: ^6.2.5
  vibration: ^1.8.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: 'assets/icon.png'
  android_12:
    color: "#000000"
    image: 'assets/icon.png'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon_128x128.png
    - shorebird.yaml
