name: Global workflow

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml

      - run: flutter pub get
      - run: dart analyze . --fatal-infos --fatal-warnings
      - run: dart format --set-exit-if-changed .
      - run: dart run dart_code_linter:metrics analyze lib
      - run: dart run dart_code_linter:metrics check-unnecessary-nullable lib
      - run: dart run dart_code_linter:metrics check-unused-files lib
      - run: dart run dart_code_linter:metrics check-unused-l10n lib
      - run: dart run dart_code_linter:metrics check-unused-code lib