name: Global workflow

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: dart analyze . --fatal-infos --fatal-warnings
      - run: dart format --set-exit-if-changed .